services:

  OurHomeApp:
    container_name: OurHome
    image: milenzapryanov/ourhome:latest
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ourhome?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - mail_password=${MAIL_PASSWORD}
      - mail_username=${MAIL_USERNAME}
    volumes:
      - ourhome-files:/OurHome/src/main/resources/static
    networks:
      - ourhome_network

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ourhome
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 3306:3306
    volumes:
      - ourhome-data:/var/lib/mysql
    networks:
      - ourhome_network

networks:
  ourhome_network:
volumes:
  ourhome-data:
  ourhome-files:

# RUN APP
# docker-compose up -d